version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
    ports:
      - 9999:9999
    environment:
      DATABASE_HOSTNAME: postgres
    entrypoint: ["/app/docker-entrypoint.sh", "mix", "phx.server"]

  postgres:
    container_name: postgres-dev
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - "./postgres-data-dev:/var/lib/postgresql/data"
