version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    environment:
      MIX_ENV: prod
      PHX_SERVER: true
      DATABASE_URL: ecto://postgres:postgres@localhost/rinha
      PORT: 9999
      DATABASE_POOL_SIZE: 10
      DATABASE_TIMEOUT: 5000
      DATABASE_QUEUE_TARGET: 200
      DATABASE_QUEUE_INTERVAL: 4000
      SECRET_KEY_BASE: xUZ2aYKI10TzUGY4juCkDIpip9LaDi8KOj0emd8HOHiFZh2zKT5sLXg+0/wzHfnw
      ERL_MAX_PORTS: 4096
    network_mode: host
    depends_on:
    - postgres
    command: ["migrate_and_release"]
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '1.5GB'

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    network_mode: host
    volumes:
    - ./postgresql.conf:/etc/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '1.5GB'
