version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
    expose:
      - 4000
    ports:
      - "4000:4000"
    environment:
      DATABASE_HOSTNAME: postgres
    networks:
      - network
    entrypoint: /app/docker-entrypoint.sh
  postgres:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - network
networks:
  network:
    driver: bridge
