version: "3.8"

services:
  app:
    user: ${USER_ID}:${GROUP_ID}
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
    ports:
      - 9999:9999
    environment:
      HOME: /app
      MIX_HOME: /app
      DATABASE_HOSTNAME: postgres
    entrypoint: ["/app/docker-entrypoint.sh", "mix", "phx.server"]

  postgres:
    container_name: postgres-dev
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
