version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
    ports:
      - 4000:4000
    environment:
      DATABASE_HOSTNAME: postgres
    entrypoint: ["/app/docker-entrypoint.sh", "mix", "phx.server"]
  postgres:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
networks:
  default:
    driver: bridge
